version: '3.8'

services:
  tomee:
    image: mim-web:latest
    container_name: mim-web
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.security.auth.login.config=/usr/local/tomee/conf/jaas.config